# Generated by Django 6.0.1 on 2026-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
    ]
